export type RootStackParamList = {
  Intro: undefined;
  Welcome: undefined;
  Register: undefined;
  Verify: undefined;
  Login: undefined;
  Home: undefined;
  Main: undefined;
  Auth: undefined;
  ProductDetails: { productId: string };
  MainTabs: undefined;
  ListingScreen: undefined;
  Cart: undefined;
  Wishlist: undefined;
  OrderHistory: undefined;
  OrderPending: undefined;
  OrderProcessing: undefined;
  OrderShipped: undefined;
  OrderDelivered: undefined;
  OrderCancelled: undefined;
  OrderRefunded: undefined;
  Profile: undefined;
  EditProfile: undefined;
  CheckoutScreen: undefined;
};
